In [8]:

import tensorflow as tf
import numpy as np
print(tf.__version__)

2.9.2


In [2]:
temp = [ 0., 0., 1., 0., 0.,2., 1., 1., 0., 0.]
values = tf.reshape(temp, [1,1,2,5])
# final 5 elements -> 2 lists-> 1 list -> 1 list

In [3]:
values
# LAZY evaluation
# TF-> complete picture only, then execution within a TF session

<tf.Tensor: shape=(1, 1, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 1., 0., 0.],
         [2., 1., 1., 0., 0.]]]], dtype=float32)>

Lazy v/s Eager Evaluation

ops. --------  Lazy.-----  Eager. 

a=1 ----------- OK -------- 1

b=2 ----------- OK ------- 2

c= a + b ------ OK ------- 3

print(c) ------ EXECUTE()->"3" -------- "3"


In [5]:
avgpool = tf.nn.pool(input=values, window_shape=(1,2), 
                     pooling_type='AVG', padding='VALID')
maxpool = tf.nn.pool(input=values, window_shape=(1,2), 
                     pooling_type='MAX', padding='VALID')

In [6]:
avgpool

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1. , 0.5, 1. , 0. , 0. ]]]], dtype=float32)>

In [7]:
maxpool

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[2., 1., 1., 0., 0.]]]], dtype=float32)>